name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Build Java Application
        run: |
          mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t myapp .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "saralaaa" --password-stdin

      - name: Tag Docker Image
        run: docker tag myapp saralaaa/myjavaapp:latest

      - name: Push Docker Image to Docker Hub
        run: docker push saralaaa/myjavaapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.JAVA }}" | docker login -u "saralaaa" --password-stdin

      - name: Pull Docker Image
        run: docker pull saralaaa/myjavaapp:latest

      - name: Deploy Docker Image
        run: |
          docker run -d -p 8080:8080 --name myjavaapp saralaaa/myjavaapp:latest
