name: Java 1.8 CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: |
          docker build -t myjavaapp .
          docker tag myjavaapp saralaaa/myjavaapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.JAVA }} | docker login -u saralaaa --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push saralaaa/myjavaapp:latest
